# Generated by Django 3.0.4 on 2020-03-20 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default=1, max_length=64, verbose_name='Brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(default=1, verbose_name='Car_Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=1, max_length=64, verbose_name='Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(db_index=True, default=1, max_length=64, verbose_name='Vin'),
            preserve_default=False,
        ),
    ]
