# Generated by Django 3.0.4 on 2020-03-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200320_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(choices=[(1, 'Sedan'), (2, 'Hatchback'), (3, 'Universal'), (4, 'Coupe')], verbose_name='Car_Type'),
        ),
    ]
